### ISSUE TITLE
nextScrollId bug

### ISSUE THREAD

**Issue by 0x1111** [wmh/jquery-scrollbox#17]
1.bug
I set autoPlay to true, so it will run code below and create a timer every time,
=>  nextScrollId = setTimeout(forward, config.delay * 1000);

But when I trigger 'forwardHover' event, it will create  another nextScrollId timer.
Maybe we should clearTimeout(nextScrollId) when you set it.

Like below:
http://jsfiddle.net/pobknpwm/
It will go one step in 5 seconds, but when i hover in and hover out the button, it will run faster next time.

2. advise
Could you add a callback after one step?

sorry for my poor english...

**Comment by wmh** [comment]
Callback functions are ready in v1.3.0:
```js
$('#demo').scrollbox({
  afterForward: function (data) {
    console.log(data.currentFirstChild);
    if (data.switchCount >= 3) {
      this.trigger('backward');
    }
  },
  afterBackward: function (data) {
    console.log(data);
  }
});
```
