### ISSUE TITLE
Stop looping

### ISSUE THREAD

**Issue by dns-project** [wmh/jquery-scrollbox#20]
Hi, Dear Developer!)
I need to stop endless looping, that's elements would stop scrolling when carousel achieves the last element, can you help me?
Thank You!)

**Comment by wmh** [comment]
I'll try to add this feature.

**Comment by wmh** [comment]
With v1.3.0 you can use the new config to setup non-infinite Loop: 
```js
$('#demo').scrollbox({
  infiniteLoop: false,
  switchAmount: 3
});
```

**Comment by dns-project** [comment]
oh) thank you kind man)))

**Comment by wmh** [comment]
You are welcome :smile:
