### ISSUE TITLE
Starting from position

### ISSUE THREAD

**Issue by yarontorbaty** [wmh/jquery-scrollbox#23]
First let me say this is an amazing work!
Issue - I'd like to save the current item number or list position that's being displayed in the user's browser data and start displaying the items from there. 
The purpose is that when a user exits the page and then revisits - the list will start from it was last paused and not from the beginning.
Is it possible in the current version?

**Comment by wmh** [comment]
Yes. you can use [callback function](https://github.com/wmh/jquery-scrollbox#callback-functions) and use cookie to save the current item. When user visits next time, read the current item from back-end and show the correct list order.
