### ISSUE TITLE
Random start?

### ISSUE THREAD

**Issue by maya77** [wmh/jquery-scrollbox#25]
Can we start from random line (\<li>) on page refresh instead of going back to the first one each time?

Please add this if not available in current version. Thank You very much in advance.

**Comment by maya77** [comment]
Please help with this. Thanks.

**Comment by wmh** [comment]
Hi, this could be done on server side, would be better than do it on client side.

**Comment by MKBharti** [comment]
How I could change random (true /false) images? The image should be displayed in a sequential manner as in my HTML.
