### ISSUE TITLE
Adding a fourth li seems to break my example

### ISSUE THREAD

**Issue by JohnF2000** [wmh/jquery-scrollbox#26]
I've inherited the maintenance of a site that uses query-scrollbox that has three li items.

I added a fourth by copying one of them, and changed the eq to eq(3)

but it does not behave well.

I'm sure I missed something easy.

Any clues would be greatly appreciated.

**Comment by wmh** [comment]
I don't know what do you mean by 'changed the eq'? Maybe this action is not required. Could you give any example for that?

**Comment by JohnF2000** [comment]
I've since discovered that there are two instances that need to be addressed: the script and the list item itself. I just overlooked that.  thanks for checking
