### ISSUE TITLE
Forward Button not working

### ISSUE THREAD

**Issue by TheDrifter254** [wmh/jquery-scrollbox#27]
Hi, 
I hope you can help me fix a bug I've got. I've included it on my page with the code below:

<script src="http://wmh.github.io/jquery-scrollbox/jquery.scrollbox.js"></script> in the head

<script type="text/javascript">
$(function () {

  $('#demo5').scrollbox({
    direction: 'h',
    distance: 134
  });
  $('#demo5-backward').click(function () {
    $('#demo5').trigger('backward');
  });
  $('#demo5-forward').click(function () {
    $('#demo5').trigger('forward');
  });

});
</script>

I've set it up on http://www.kenyabuzz.com/movies/test/now-showing#

**Comment by wmh** [comment]
Please refer to the following style guide:
![Style Guide](https://camo.githubusercontent.com/bc855626f1d2c92a186e1a73ed7b6f7811f6bdb6/687474703a2f2f776d682e6769746875622e696f2f6a71756572792d7363726f6c6c626f782f696d672f776972656672616d652e706e67)

You have to set a larger width to the ul element.
