### ISSUE TITLE
how to scroll horizontal?

### ISSUE THREAD

**Issue by prajktyeole** [wmh/jquery-scrollbox#28]
<?php
/**
 * @package     Joomla.Site
 * @subpackage  mod_articles_news
 *
 * @copyright   Copyright (C) 2005 - 2014 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

$scrollbox = '<script src="templates/darkblue/js/jquery.scrollbox.min.js"></script>' ."\n";
$scrollbox .= '<script>' ."\n";
$scrollbox .= 'jQuery(document).ready(function(){' ."\n";
$scrollbox .= 'jQuery(".newsflash.horizontal-scroll").scrollbox({ linear: true, step: 1, delay: 0, direction: "h", speed: 50 });' . "\n";
$scrollbox .= '});' ."\n";
$scrollbox .= '</script>' ."\n";

$doc = JFactory::getDocument();
$doc->addCustomTag($scrollbox);

?>
<div class="newsflash horizontal-scroll hor-parent-class">
<ul class="hor-list-class">
<?php
foreach ($list as $item) :
	require JModuleHelper::getLayoutPath('mod_articles_news', '_item-hs');
endforeach;
?>
</ul>
</div>

**Comment by wmh** [comment]
Please see examples or show me your code on jsbin.

**Comment by prajktyeole** [comment]
<?php
/**
 * @package     Joomla.Site
 * @subpackage  mod_articles_news
 *
 * @copyright   Copyright (C) 2005 - 2014 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;


$scrollbox = '<script src="templates/darkblue/js/jquery.scrollbox.min.js"></script>' ."\n";
$scrollbox .= '<script>' ."\n";
$scrollbox .= 'jQuery(document).ready(function(){' ."\n";
$scrollbox .= 'jQuery(".newsflash.horizontal-scroll").scrollbox({ linear: true, step: 1, delay: 0, direction: "h", speed: 50 });' . "\n";
$scrollbox .= '});' ."\n";
$scrollbox .= '</script>' ."\n";

$doc = JFactory::getDocument();
$doc->addCustomTag($scrollbox);

?>
<div class="newsflash horizontal-scroll hor-parent-class">
<ul class="hor-list-class">
<?php
foreach ($list as $item) :
	require JModuleHelper::getLayoutPath('mod_articles_news', '_item-hs');
endforeach;
?>
</ul>
</div>

**Comment by prajktyeole** [comment]
This is the code i've written for joomla template overide

**Comment by wmh** [comment]
Sorry, but I didn't see anything here, not even the js library file.

**Comment by prajktyeole** [comment]
![q](https://cloud.githubusercontent.com/assets/14156850/10358144/c73fca0a-6da7-11e5-8e93-1f5f023f64ff.png)

**Comment by prajktyeole** [comment]
check now

**Comment by prajktyeole** [comment]
okay tell me, we have to add " direction: 'h' " for horizontal scrolling of text right?

**Comment by wmh** [comment]
1. add direction option
2. style your html elements correctly
