### ISSUE TITLE
Not working in Chrome/Firefox/Safari when copied to server

### ISSUE THREAD

**Issue by ScottMack** [wmh/jquery-scrollbox#32]
Using SharePoint 2010 (PC).

Hi!  ScrollBox works as expected when copied locally to my C drive and viewed in any browser, but when I copy the unedited files to the server, the animations no longer work in Chrome/Firefox/Safari and I get the "Only secure content is displayed" message in IE (animations work after clicking "Show all content").

Any suggestions?

**Comment by wmh** [comment]
Where's your JavaScript files?

**Comment by ScottMack** [comment]
Hunter -- thanks for the quick response.  The files are the same files on this site.  However, I was able to figure it out late last night.  Once I updated from http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js to https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js it worked as expected.

**Comment by wmh** [comment]
:+1:
