### ISSUE TITLE
backward / forward doesnt work with direction vertical

### ISSUE THREAD

**Issue by ShaimyWinda** [wmh/jquery-scrollbox#39]
Hello,

I try your Scrollbox but in vertically, doesnt work very well

https://fr.preprod.moondreamwebstore.fr/rideau-separation-de-pieces/rideau-phonique-separation-de-pieces-blanc-mc720-576-2286.html

Do you know why ?

Thanks

**Comment by wmh** [comment]
To fix it:
1. give .js-qv-mask a fixed height, say 44.5rem;
2. enlarge height of .js-qv-mask > ul, say 65rem;
3. remove width of .js-qv-mask > ul

**Comment by ShaimyWinda** [comment]
OMG thank you so much !!! I have been working on this problem for 6 hours
